src/UI/MainWindow.vala, src/Widgets/Sheet.vala
We should be able to scroll the Sheet in whatever direction we want, so added a ScrolledView and a Viewport, maybe it would be better to handle that inside the Sheet widget, allowing us to keep the columns/rows header fixed will the sheet scrolls. :)
=> [WIP] Add scroll support.

src/Functions/meson.build, src/Models/Cell.vala, src/Models/HistoryAction.vala, src/Models/Page.vala, src/Models/Spreadsheet.vala, src/Models/meson.build, src/Parser/AST/Expression.vala, src/Services/CSV/CSVGrammar.vala, src/Services/CSV/CSVParser.vala, src/Services/CSV/CSVWriter.vala, src/Services/CSV/meson.build, src/Services/Formula/AST/CallExpression.vala, src/Services/Formula/AST/CellReference.vala, src/Services/Formula/AST/Expression.vala, src/Services/Formula/AST/NumberExpression.vala, src/Services/Formula/FormulaGrammar.vala, src/Services/Formula/FormulaParser.vala, src/Services/Formula/meson.build, src/Services/Parsing/Evaluator.vala, src/Services/Parsing/Grammar.vala, src/Services/Parsing/Lexer.vala, src/Services/Parsing/Parser.vala, src/Services/Parsing/Token.vala, src/Services/Parsing/meson.build, src/Services/meson.build, src/UI/MainWindow.vala, src/UI/meson.build, src/Widgets/Sheet.vala, src/Widgets/meson.build, src/meson.build
Added a CSV Parser and Writer, and use them to open/save CSV.
Also reorganized the repository.
=> Save and open CSV

src/Models/HistoryAction.vala
The app crashes by trying to input a number into a cell.
* Fix that the app crashes by trying to input a number into a cell
* Fix that redo is not work
=> Fix that the app crashes by trying to input a number into a cell

src/App.vala, src/UI/MainWindow.vala
Fixes #37 
* Alt+Home to back to welcome view
* Ctrl+O to open sheet
* Ctrl+S to save sheet
* Ctrl+Z to undo
* Ctrl+Shift+Z to redo
* F2 to edit expression entry
* ~Delete to blank the selected cell (This took long time implementing)~
* Esc to back the focus from expression entry
=> Add shortcut keys

po/com.github.ryonakano.spreadsheet.pot, src/Models/Cell.vala, src/UI/MainWindow.vala, src/Widgets/Sheet.vala
I'm not sure if this is how it should be done, so feel free to dismiss the pull request if there could be a better way of doing this.
=> Delete key clears the cell content

src/Models/Cell.vala
=> Fix blank cells are displayed as 'Error'

src/App.vala, src/Services/HistoryManager.vala, src/UI/MainWindow.vala
=> Handle multiple windows

src/UI/MainWindow.vala
Implement the following features mentioned in #82:
- Add file to recents when a file is opened
- Add file to recents when a file is saved
**Merge into `recent-files`, not `master`**
=> Update recent files list when opening/saving files

src/Models/Page.vala, src/Models/Spreadsheet.vala
For consistency with other source files or elementary projects
=> Properties at the top of classes

po/POTFILES, src/Models/Function.vala
* Properties at the top of classes
* Indentation
* Make the string "No documentation" translatable
=> Function: Coding style and l10n

src/Models/Cell.vala, src/Models/HistoryAction.vala
The build seems to pass without these lines.
=> Remove unused namespaces in the using directive

src/Models/CellStyle.vala, src/Models/FontStyle.vala, src/Widgets/StyleModal.vala
* Remove unnecessary variables
* DRY in long Gdk.RGBA values
=> StyleModal: Coding style

src/UI/MainWindow.vala
* Remove unnecessary using decretive
* Less scope (`public` to `private` or `var`)
* Explict access modifiers
* `update_header ()` in more appropriate (related) place
* Use
```
var toolbar = new Grid ();
toolbar.border_width = 10;
toolbar.column_spacing = 10;
```
instead of
```
var toolbar = new Grid () {
border_width = 10,
column_spacing = 10
};
```
(I don't know how to say this ^^;)
=> MainWindow: Coding Style

debian/changelog, debian/control, debian/copyright
=> deb-packaging: Rename everything to 'elework'

src/UI/MainWindow.vala
=> Use a tilde to represent the home directory for headerbar

src/UI/MainWindow.vala
=> Fix window does not open in a saved size

meson.build, src/App.vala, src/Config.vala.in
Borrowed the code written by tintou in elementary/screenshot
=> Fix translation is not loaded in Flatpak

README.md, data/meson.build, meson.build
See also: https://mesonbuild.com/Reference-manual.html#join_paths
Also remove a version restriction for glib that does not seem to affect anything while we're here
=> Use '/' instead of join_paths

src/UI/MainWindow.vala
This supports dark style and more looks matching in Pantheon
=> Use FileChooserNative

data/Application.css, src/UI/MainWindow.vala
Much more similar to [the mockup](https://www.deviantart.com/bassultra/art/Spreadsheet-363147552)
=> Improve appearance of function list button

meson.build, po/POTFILES, src/App.vala, src/Models/Function.vala, src/Models/FunctionManager.vala, src/Services/Formula/AST/CallExpression.vala, src/Services/Formula/FormulaGrammar.vala, src/UI/MainWindow.vala
Also lessen scopes of class members while we're here
=> Make functions list independent from App class

src/App.vala
Also remove unused using while we're here
=> Setup l10n in main

src/App.vala, src/UI/MainWindow.vala
This is more flexible to add/remove actions
=> App: Use GLib.ActionEntry instead of SimpleAction

data/spreadsheet.gschema.xml, src/App.vala, src/UI/MainWindow.vala
GTK 4 preparation. Window managers are responsible for managing window positions in GTK 4
=> Drop feature to save & restore window position

src/Models/CellStyle.vala, src/Models/FontStyle.vala, src/Widgets/Sheet.vala, src/Widgets/StyleModal.vala
- Add definitions for default values and range
- Consistent variable naming
- Consistent I/F
=> Refactor *Style

src/Functions/Basic.vala
- Avoid `else if` if possible
- Add a newline for different code blocks
- Don't call methods twice with the same parameter
=> Basic: Refactor

src/Services/Formula/AST/CallExpression.vala, src/Services/Formula/AST/CellReference.vala, src/Services/Formula/AST/NumberExpression.vala, src/Services/Formula/AST/TextExpression.vala
- Remove unnecessary using
- Unify variable naming
- Lessen scope
- Show error in the log instead of cell content (not a refactoring actually though)
- Explicit the constructor
- Unify use of using in the subclasses
- Use GObject-style construction
=> Refactor Expression subclasses

src/AlphabetGenerator.vala
- Explicit namespace if it's short
- Correct comment indentation
- Avoid `else` if possible
- Correct comment position
=> Refactor AlphabetGenerator

src/UI/MainWindow.vala
=> MainWindow: Show an error dialog if open failed

src/UI/MainWindow.vala
These methods are removed in GTK 4
=> MainWindow: Replace run() of Gtk.Dialog and Gtk.NativeDialog

src/UI/MainWindow.vala
=> MainWindow: Fix missing show_all() after save as

src/Widgets/ActionBar.vala
=> ActionBar: Don't subclass Gtk.ActionBar

README.md, data/spreadsheet.appdata.xml.in
=> master → main

data/Application.css, src/UI/MainWindow.vala
Because it's designed to use with Gtk.Popover
=> Use Gtk.MenuButton for popover button

src/UI/MainWindow.vala, src/UI/WelcomeView.vala
=> Replace Gtk.Container.add()

src/UI/MainWindow.vala, src/Widgets/StyleModal.vala
=> Replace Gtk.Container.border_width

data/spreadsheet.desktop.in
- Explicit version
- Remove duplicated, useless, and not required GenericName
- Remove duplicated, useless, and confusing (`Book`) Keywords
=> Improve desktop file

src/App.vala, src/Models/CellStyle.vala, src/Models/FontStyle.vala, src/Services/CSV/CSVParser.vala, src/Services/CSV/CSVWriter.vala, src/Services/Formula/AST/CallExpression.vala, src/Services/Formula/FormulaGrammar.vala, src/Services/Parsing/Lexer.vala, src/Services/Parsing/Parser.vala, src/UI/MainWindow.vala, src/UI/WelcomeView.vala, src/Widgets/Sheet.vala, src/Widgets/StyleModal.vala
Fixes #193
- Do not omit well-known namespaces like Gtk, Gdk, Cairo, etc.
- Implicit the GLib namespace
- Follow our guideline of namespace use
- Remove unused usings
=> Review use of namespace

src/UI/MainWindow.vala
This allows hiding blank text file with ".csv" suffix hidden in the file dialog.
=> Use mimetype for file filter
