elework/Spreadsheet

- src/UI/MainWindow.vala
At the moment, clicking any buttons in welcome screen opens a new sheet. This PR let us create an empty sheet by clicking "New Sheet" and open a saved presentation by clicking "Open a file".
* Allow to open existing file from welcome screen
* Fix unhandled errors
> Allow to open existing file from welcome screen

- data/xyz.gelez.spreadsheet.gschema.xml
- meson.build
- meson/post_install.py
- src/App.vala
- src/UI/MainWindow.vala
Fixes #42 
This PR allows the app to save window width, height, x position, y position, and state (whether window is maximized) and restore them when we run the app again.
* Add a schema to save window width, height, x position, y position, and state
* Add `meson/post_install.py` to load the schema after installation
* Divide MainWindow method whether the app is first run or not
> Save window size, position and state

- data/icons/128/xyz.gelez.spreadsheet.svg
- data/icons/32/xyz.gelez.spreadsheet.svg
- data/icons/48/xyz.gelez.spreadsheet.svg
- data/icons/64/xyz.gelez.spreadsheet.svg
- data/meson.build
- meson.build
- meson/post_install.py
* Add 32, 48 and 64px icons (Fixes #28)
* Update the app icon and its color to respect the elementary HIG using [micahilbery/elementary-icon-templates](https://github.com/micahilbery/elementary-icon-templates)
* Fill: gradation (upper: #9bdb4d, lower: 68b723)
* Stroke: #206b00 in 50% opacity
Even if this PR is merged, the old app icon will be still used in the dock, because these new icons are not assigned to use in any codes yet. In future another PR I'll remove the current (old) icon, add .desktop and .appdata.xml files and assign these icons there. With this another step, the app will use these new icons.
> Add icons for other pixels & New icons

- src/UI/MainWindow.vala
* Adjust the spacing between the label of style_toggle and the black square
* Set the alignment of the label of style_toggle to left
* Set margin for the back square
> Improve the looks of style_toggle

- src/Widgets/Sheet.vala
Fixes #6
(I'm not good at math, so there might be some mistakes…)
Sorry for my messy handwriting and figures :disappointed_relieved:
* `left_margin` is the width of the leftmost cells in which has row numbers
* `WIDTH` is the width of the cells excluding the leftmost one
* `HEIGHT` is the height of all cells
* `BORDER` is the thickness of the stroke of cells
```
x = left_margin / 2 - extents.width / 2;
```
```
y = BORDER + HEIGHT * i + HEIGHT / 2 + extents.height / 2;
```
```
x = left_margin + BORDER + WIDTH * i + WIDTH / 2 - extents.width / 2;
```
```
y = BORDER + HEIGHT / 2 + extents.height / 2;
```
> Center letters and numbers in the Sheet widget

- src/Widgets/StyleModal.vala
As requested at https://github.com/ryonakano/Spreadsheet/pull/64#discussion_r296662739:
> In the context of the app the "Fonts" and the "Cells" attribute are applied on one specific cell si there is no reason to use plural form.
> Don't use plural for cell/font settings label

- src/UI/MainWindow.vala
As requested at https://github.com/ryonakano/Spreadsheet/pull/64#discussion_r296661383:
> As far as I know the spreadsheet softwares uses "sheet" as a page.
---
At first I hesitated to make this change because I felt naming a new instance of `Page` object as "Sheet" may not make sense, but I found we do essentially the same thing in the following code and there we name a new instance of `Page` object as "Sheet", so I decided to make this PR.
https://github.com/ryonakano/Spreadsheet/blob/3f5f64faff2322bf1a6d940f02908bbc80dc7cfe/src/Services/CSV/CSVParser.vala#L24-L32
> Use commonly used word 'sheet' instead of 'page'

- src/App.vala
* Fix a typo: substruct to subtract
* The words "cosinus", "sinus" seem to be a French
I'm not good at math, so I wonder why "**arg** tangent" is not "**arc** tangent" like other trigonometric functions (arc cosine and arc sine). Should we also fix this?
```vala
functions.add (new Function ("arccos", Functions.arccos, _("Gives the arc cosine of a number")));
functions.add (new Function ("arcsin", Functions.arcsin, _("Gives the arc sine of a number")));
functions.add (new Function ("arctan", Functions.arctan, _("Gives the arg tangent of a number")));
```
> Fix typos in the function descriptions

- src/Widgets/Sheet.vala
Fixes #73
As commented in https://github.com/ryonakano/Spreadsheet/pull/11#issuecomment-298685540, requesting the widget size seems to allow to scroll, but I got another error message other than the ones in #52 for some reason :man_shrugging:
```
(com.github.ryonakano.spreadsheet:24449): Gtk-CRITICAL **: 12:47:38.257: gtk_box_gadget_distribute: assertion 'size >= 0' failed in GtkScrollbar
r
```
> Support scrolling sheets

- src/Widgets/Sheet.vala
There seems to be [a useful method](https://valadoc.org/gdk-3.0/Gdk.cairo_set_source_rgba.html) that would be an alternative to our custom method `set_color`. I believe the color doesn't change between `master` and this branch…
> Use convenient Gdk.cairo_set_source_rgba method

- src/Models/CellStyle.vala
- src/Widgets/Sheet.vala
- src/Widgets/StyleModal.vala
According to [GDK 3 Reference Manual for Gdk.RGBA](https://developer.gnome.org/gdk3/stable/gdk3-RGBA-Colors.html):
> All values are in the range from 0.0 to 1.0 inclusive. So the color (0.0, 0.0, 0.0, 0.0) represents transparent black and (1.0, 1.0, 1.0, 1.0) is opaque white.
So `{255, 255, 255, 1}` seems to be an invalid value, although it renders as white.
Also, make sure to specify `1` for alpha values to render the default stroke and fill colors correctly:
> Use the correct values for Gdk.RGBA

- src/App.vala
- src/UI/MainWindow.vala
- src/UI/TitleBar.vala
The app destroys the buttons in the titlebar every time it shows the welcome screen at the moment, which may not be efficient. This PR toggles their visibility by using `visible` and `no_show_all` properties instead.
> TitleBar: Toggle visibility instead of destroy

- data/Application.css
- data/meson.build
- data/spreadsheet.gresource.xml
- meson.build
- src/UI/MainWindow.vala
Fix visibility issue of the font color square in style_toggle when inactive. This issue only happens on the new stylesheet called Greenfield that will come with the next version of elementary OS.
> Fix font color in style_toggle is not drawn when inactive with greenfield

- data/Application.css
- src/Widgets/StyleModal.vala
- `Granite.HeaderLabel` now sets left and right margins in popovers and it makes the layout broken so disabled it
- `Granite.HeaderLabel` has the property `halign` to `Gtk.Align.START` by default so removed it
- Readable variable and function name
> StyleModal: Fix HeaderLabel layout and coding style

- com.github.elework.spreadsheet.yml
It works seemingly perfectly, and has permissions for dark/light mode switching and Documents folder access. Thanks to the lack of any extra libs it's super minimal
> Add elementary OS 6 Flatpak manifest

- com.github.elework.spreadsheet.yml
From https://docs.flatpak.org/en/latest/flatpak-builder-command-reference.html:
> Note, "app-id" is deprecated and preserved only for backwards compatibility.
> Flatpak: Use id instead of deprecated app-id

- meson.build
- meson_options.txt
I prefer vim/neovim than VSCode now
> meson: Remove enable_debug option

- src/App.vala
- src/UI/MainWindow.vala
So that it's applied to windows/dialogs independent from MainWindow, while they don't exist at the moment
> Setup OS-wide dark preference in startup

- src/UI/MainWindow.vala
- src/Widgets/FunctionListRow.vala
- Subclass Gtk.ListBoxRow directly instead of Gtk.EventBox (part of #133)
- Lessen scope of `function`
- Use GObject-style construction
- Explicit namespace if it's short
- Change cursor shape in the class instead of the caller side
> FunctionListRow: Rewrite with GTK 4 prep

- src/Widgets/StyleModal.vala
- Do not create new instance in methods
- GTK 4 preparation: use `Gtk.Container.child` instead of `Gtk.Container.add()`
- Avoid long lines
- Use the constants added in #149
> Refactor StyleModal

- src/AlphabetGenerator.vala
- src/Services/Formula/FormulaParser.vala
`=AB1` refers to B1 because the index results to 1.
Also left comments and reviewed variable names while I understood the original code.
> AlphabetGenerator: Fix wrong index after "AA"

- src/UI/WelcomeView.vala
Because it is RecentsManager that is responsible for keeping in sync with GSettings
> WelcomeView: Bind with property instead of GSettings

- src/Widgets/Sheet.vala
> Sheet: Subclass Gtk.DrawingArea instead of Gtk.EventBox

- src/Services/RecentsManager.vala
- src/UI/MainWindow.vala
- Remove redundant `recents_`; it's implicit about recent files because these methods are in RecentsManager
- Use concrete words instead of generic ones: `load` instead of `init` and `prepend` instead of `add`
> RecentsManager: Shorten and readable method names

- src/App.vala
- src/UI/MainWindow.vala
- src/Widgets/TitleBar.vala
- DRY Accels
- Remove unused `MainWindow.ACTION_NAME_NEW`
- Fix passing non-null-terminated arrays to `Gtk.Application.set_accels_for_action()`
> DRY Accels

- src/UI/MainWindow.vala
This PR fixes the titlebar label has no `.csv` suffix when creating new file.
> MainWindow: Fix missing suffix in the titlebar when new file

- data/Application.css
- meson.build
- src/UI/MainWindow.vala
- src/Widgets/RoundedSquare.vala
Towards #132
Create a new class based on Gtk.DrawingArea instead of hacky code in the `draw()` signal handler.
> Introduce RoundedSquare

- src/UI/MainWindow.vala
- src/Widgets/Sheet.vala
> Handle autosave in MainWindow
